<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GPsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            [
                "id" => 1,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "mon",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 2,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "tue",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 3,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "wed",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 4,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "thur",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 5,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(250,330),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "fri",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 6,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(300,430),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "sat",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 7,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(300,430),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "sun",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week"),
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 8,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "mon",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 9,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "tue",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 10,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "wed",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 11,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(170,230),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "thur",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 12,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(250,330),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "fri",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 13,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(300,430),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "sat",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id" => 14,
                "daily_stock_purchase" => rand(80,130),
                "intake" => rand(300,430),
                "budget_estimate" => 0,
                "GP(£)" => 800,
                "GP(%)" => 70,
                "day" => "sun",
                "date" => Carbon::today()->subWeek(),
                "week_id" => 14,
                "unique_week_id" => strtotime("monday last week") - 604800,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
        ];
            DB::table('gps')->insert($data);
    }
}
